import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";
import AppAnimations from "../components/ui/AppAnimations";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="page-layout min-h-screen">
            {Header && (
              <header className="page-header">
                <Header />
              </header>
            )}
            {Navbar && (
              <aside className="page-sidebar">
                <Navbar />
              </aside>
            )}
            <main className="page-main">
              <Toaster position="bottom-right" reverseOrder={false} />
              <AppAnimations>{children}</AppAnimations>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
